name: Daily Monolith Run

on:
  schedule:
    - cron: "45 13 * * *"  # 8:45 AM ET
    - cron: "30 14 * * *"  # 9:30 AM ET
    - cron: "30 16 * * *"  # 11:30 AM ET
    - cron: "30 19 * * *"  # 3:30 PM ET
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      TRADIER_TOKEN: ${{ secrets.TRADIER_TOKEN }}
      TRADIER_ACCOUNT_ID: ${{ secrets.TRADIER_ACCOUNT_ID }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      OFFLINE: "0"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monolith
        run: python monolith.py run
